language: ruby
cache: bundler
rvm:
- 2.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
# deploy:
#   provider: gcs
#   access_key_id: ${access_key_id}
#   secret_access_key:
#     secure: ${secret_access_key}
#   bucket: www.brooklinebooksmith.com
#   acl: public-read
#   detect_encoding: true # <== default is false
#   cache_control: "no-cache"
#   local-dir: _site
#   skip_cleanup: true
#   on:
#     repo: sonnetmedia/brooklinebooksmith.com
#     branch: gh-pages
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy --token "$FIREBASE_TOKEN"