language: ruby
cache: bundler
rvm:
- 2.1
install: 
- bundle install 
- npm install -g firebase-tools
script: bundle exec jekyll build
after_success:
  firebase deploy --token "${FIREBASE_TOKEN}"

branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false 