title: Bud Parr
description: 'Bud Parr is a web designer, developer and strategist. For 15 years his efforts have focused on the cultural and human rights sectors, including work for New Directions, HarperCollins, Other Press, Retro Report, The American Bar Association, The Royal Kingdom of the Netherlands, and numerous others.'

exclude: ['readme.md','license.md','Gemfile']

twitter:
  username: budparr
logo: 'uploads/bpny_1000x774.jpg'
url: https://www.budparr.com

production: true
gems:
  - jekyll-seo-tag

# options (data)
google_analytics_id: UA-30899180-2
addthis_id: ra-52e194380e6e5e78


collections:
  landing_pages:
    output: true
    permalink: /awesome/:path/
  my_collection:
    output: true
    permalink: /awesome/:path/
