title: Bud Parr
description: 'Bud Parr is a web designer, developer and strategist.'

exclude: ['readme.md','license.md','Gemfile']
paginate:            5
twitter:
  username: budparr
logo: 'uploads/bpny_1000x774.jpg'
url: https://www.budparr.com

production: true
gems:
  - jekyll-seo-tag
  - jekyll-paginate

# options (data)
google_analytics_id: UA-30899180-2
addthis_id: ra-52e194380e6e5e78


collections:
  landing_pages:
    output: true
    permalink: /awesome/:path/
  my_collection:
    output: true
    permalink: /awesome/:path/


compress_html:
  ignore:
    envs: [development]
  profile: false
