# jekyll-seo-tag
title: Bud Parr
description: 'Bud Parr is a web designer, developer and strategist.'
url: "https://www.budparr.com" # the base hostname & protocol for your site
author: Bud Parr
twitter:
  username: budparr
facebook:
  app_id: 
  publisher: 
  admins: 
logo: #path

short_name: BPNY
display: fullscreen


exclude: ['readme.md','license.md','Gemfile']
paginate:            5
twitter:
  username: budparr
logo: '/uploads/bpny_1000x774.jpg'
url: https://www.budparr.com

version: 3.0.3
production: true
gems:
  - jekyll-seo-tag
  - jekyll-paginate

# options (data)
google_analytics_id: UA-30899180-2
addthis_id: ra-52e194380e6e5e78


permalink: /article/:title/

collections:
  landing_pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: landing_pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post


compress_html:
  ignore:
    envs: [development]
  profile: false
