[build]
publish = "public"
command = "hugo --minify"

[build.environment]
HUGO_VERSION = "0.64.0"

[context.production.environment]
HUGO_VERSION = "0.64.0"
# Uncomment the next line when moving site to production
# HUGO_ENV = "production"
#HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_URL"

[[headers]]
for = "/*"

  [headers.values]
  Content-Security-Policy = "upgrade-insecure-requests"
  Strict-Transport-Security = "max-age=15768000"
  X-Xss-Protection = "1; mode=block"
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"


# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/
