name: Deploy Hugo to Cloudflare
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: checkout source
        uses: actions/checkout@v1
        # https://github.com/crazy-max/ghaction-hugo
      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v1
        with:
          version: latest
          extended: true
          args: --cleanDestinationDir --minify --verbose
      - name: Publish
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "production"
