# name: Deploy Hugo to Cloudflare
# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     name: Deploy
#     steps:
#       - name: checkout source
#         uses: actions/checkout@v1
#       - name: Build
#         uses: budparr/action-hugo@master
#       - name: Publish
#         uses: cloudflare/wrangler-action@1.1.0
#         with:
#           apiToken: ${{ secrets.CF_API_TOKEN }}
#           environment: "production"
