name: Update Monday.com Status
on:
  pull_request:
    types:
      [opened, closed]
    branches:
      - main
jobs:
  update_monday_job:
    runs-on: ubuntu-latest
    name: Update Monday Status
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Call Monday.com API
      uses: ./ # Uses an action in the root directory
      with:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        BOARD_ID: 1067034989
        COLUMN_ID: "status"
        submitted-status: "PR Submitted"
        merged-status: "closed"
        pull-request-body: ${{ github.event.pull_request.body }}
        merged: ${{ github.event.pull_request.merged }}
      if: contains(github.event.pull_request.body, 'pulses')